#temporary hacked-make file which allows to run tests on OS X
#
#

CC=clang++
CFLAGS=-c -w -std=c++0x \
	-I ../Classes \
	-I ../cocos2d/cocos \
	-I ../cocos2d/external/glfw3/include/mac
	
LDFLAGS=\
    -framework OpenGL \
    -framework GLKit \
    -framework CoreGraphics \
    -framework AppKit \
    -framework AudioToolbox \
    -framework AVFoundation \
    -framework OpenAL \
    -framework QuartzCore \
	-framework Foundation \
	-framework IOKit \
    -L. \
    -lcocos2d \
    -lz \
    -liconv \

OUTPUT_DIR=.
SOURCES=$(wildcard *.cpp) $(wildcard ../Classes/*.cpp) 
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=run-tests

all: $(SOURCES) $(EXECUTABLE)

clean: 
	find ./ ../Classes -name "*.o" -delete

$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $(OUTPUT_DIR)/$@

%.o: %.cpp 
	$(CC) $(CFLAGS) $< -o $@

